In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("aspekfix.xlsx")
df #cetak isi dataset

Clean Data Kategori    Label
0    ngantuk banget tunggu tugas seperti tunggu ord...  service  negatif
1                       enak banget rumah dekat gacoan  service  positif
2             oiya maaf aku lagi pengin gacoan praktis  service  positif
3                             kurang sumpit gacoan aja  service  negatif
4    wkwkwkw tapi benar ada sih beli gacoan pakai s...  service  positif
..                                                 ...      ...      ...
134           banyak pegawai tapi kurang satset gacoan  service  negatif
135                   gacoan tempat estetik dan bersih  service  positif
136                         antri banget gakuat gacoan  service  negatif
137  mau marah tapi gaenak mas di gacoan salah ante...  service  negatif
138                          pelayanan gacoan nyebelin  service  negatif

[139 rows x 3 columns]

In [2]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer 
vectorizer = CountVectorizer(decode_error="replace")
transformer = TfidfTransformer()
TFIDF = transformer.fit_transform(vectorizer.fit_transform(df['Clean Data']))

In [3]:
print(TFIDF)

  (0, 486)	0.6341960530331914
  (0, 480)	0.35448818130034426
  (0, 411)	0.3334311381195792
  (0, 335)	0.27407466715868395
  (0, 313)	0.35448818130034426
  (0, 291)	0.24173448250927254
  (0, 236)	0.2593864682610314
  (0, 140)	0.07319553492265107
  (0, 38)	0.17059862726422784
  (1, 385)	0.5765361435304182
  (1, 140)	0.11904450882721239
  (1, 121)	0.4940207778756924
  (1, 99)	0.5765361435304182
  (1, 38)	0.2774599545003382
  (2, 360)	0.47458247461911335
  (2, 350)	0.33857991768394874
  (2, 328)	0.47458247461911335
  (2, 256)	0.47458247461911335
  (2, 231)	0.30532929477541015
  (2, 140)	0.09042257880256836
  (2, 9)	0.3290529481541997
  (3, 445)	0.5416350326834384
  (3, 228)	0.5695336151315421
  (3, 140)	0.12502526863892985
  (3, 3)	0.6055011435224302
  :	:
  (134, 228)	0.47963008864783807
  (134, 140)	0.10528944927449047
  (134, 41)	0.40664900374051566
  (135, 463)	0.38879784048925975
  (135, 140)	0.11772530594716177
  (135, 130)	0.6178807081324836
  (135, 90)	0.40694527643388667
  (135, 5

In [4]:
labels = [] #membuat kolom labels
for data in df['Label']:#untuk data di df row kategori
    labels.append(data)
kolom = labels.pop

In [5]:
ktgr = [] #membuat kolom labels
for data in df['Kategori']:#untuk data di df row kategori
    ktgr.append(data)
kolom = ktgr.pop

In [6]:
#kemudian kategori diberi label
Label=[]
for i in range(len(labels)): 
    if ktgr[i] =='service' and labels[i]=='negatif':
        nilai = 4
    if ktgr[i] =='service' and labels[i]=='positif':
        nilai = 5 
    Label.append(nilai)

In [7]:
from sklearn import svm #metode untuk klasifikasi aspek / kategori
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer #untuk menghitung vsm dan tfidf #vsm =vector space model
from sklearn import metrics #metode untuk pembentukan matriks 1x1 1x2 1x3
from sklearn.metrics import accuracy_score #metod untuk pembentukan skor akurasi 
from sklearn.model_selection import KFold #metode untuk perhitungan kfold
import numpy as np 
import re #regular expression
import itertools #fungsi pengulangan tak terbatas
import matplotlib.pyplot as plt #pembentukan diagram
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC #suport vector classifier
from sklearn.metrics import classification_report

In [8]:
akurasi=[]
def avg_akurasiSVM(): ##fungsi untuk rata rata akurasi one vs rest classifier
    total = 0
    for i in range(10): 
        total = total + akurasi[i]
    print("Rata-rata akurasi keseluruhan SVM Linear adalah :", total /10)

In [9]:
from sklearn.svm import SVC #fungsi K-Fold Cross Validation melakukan insialisasi 10 kali iterasi
kFoldCrossValidation = KFold (n_splits = 10, random_state = 2, shuffle = True)

for latih, uji in kFoldCrossValidation.split(TFIDF, Label):

    print("-----------------------------")
    print("Jumlah data latih: ", len(latih)) #berapa jmlah data latih
    print("Jumlah data uji: ", len(uji)) #berapa jumlah data uji
    print("\nData Latih: \n", latih) #menampilkan data latih
    print("\nData Uji: \n", uji)#menampilkan data uji
    dataLatih1, dataUji1 = TFIDF[latih], TFIDF[uji]#proses inisialisasi dari masing2 data latih/uji dijadikan nilai tfidf lalu di copy ke variabel dataLatih/Uji1
    Label = np.array(Label)
    dataLatih2, dataUji2 = Label[latih], Label[uji]#

    SVM = SVC(kernel = 'linear', C = 1, degree = 3, gamma = 0.1)
    #SVM = SVC(kernel = 'linear')
    model = SVM.fit(dataLatih1, dataLatih2)
    prediksi = model.predict(dataUji1)

    print("\nHasil Prediksi SVM  : \n", prediksi)

    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi))

    akurasi.append(accuracy_score(dataUji2, prediksi))

    print("\nAkurasi SVM : ", accuracy_score(dataUji2, prediksi))
    print()\

    print(metrics.classification_report(dataUji2, prediksi,labels=[4,5])) #proses pembentukan confusin matrix
avg_akurasiSVM() #hasil rata rata multiclass

-----------------------------
Jumlah data latih:  125
Jumlah data uji:  14

Data Latih: 
 [  0   1   4   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  25  26  27  28  29  30  31  32  33  34  35  37  38  39  40
  41  42  43  45  46  47  49  50  51  52  54  55  56  57  58  59  60  61
  62  63  64  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
  81  83  84  85  86  87  88  90  91  92  93  94  95  96  97  98  99 100
 102 103 104 105 106 107 109 110 111 112 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138]

Data Uji: 
 [  2   3   5  24  36  44  48  53  65  82  89 101 108 113]

Hasil Prediksi SVM  : 
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4]

Confusion Matrix: 
 [[10  0]
 [ 4  0]]

Akurasi SVM :  0.7142857142857143

              precision    recall  f1-score   support

           4       0.71      1.00      0.83        10
           5       0.00      0.00      0.00         4

    accuracy                        

 119 121 122 123 124 125 126 128 129 130 132 133 134 135 136 137 138]

Data Uji: 
 [ 33  46  52  58  66  68  69  70  80  83  88 120 127 131]

Hasil Prediksi SVM  : 
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4]

Confusion Matrix: 
 [[9 0]
 [5 0]]

Akurasi SVM :  0.6428571428571429

              precision    recall  f1-score   support

           4       0.64      1.00      0.78         9
           5       0.00      0.00      0.00         5

    accuracy                           0.64        14
   macro avg       0.32      0.50      0.39        14
weighted avg       0.41      0.64      0.50        14

-----------------------------
Jumlah data latih:  125
Jumlah data uji:  14

Data Latih: 
 [  0   1   2   3   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  40
  41  43  44  45  46  47  48  49  50  52  53  54  55  56  57  58  59  60
  61  62  63  64  65  66  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  8

C:\Users\windows\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\windows\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\windows\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\windows\anaconda3\lib\site-packages\skle